name: Setup gcloud CLI

on:
  push:
    branches:
      - main

jobs:
  setup-gcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: actions/setup-gcloud@v0.5.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          version: 463.0.0

      # Additional steps specific to gcloud setup, if needed...
