name: Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set up PostgreSQL
        run: |
          sudo systemctl start postgresql.service
          sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'abcdef';"
          sudo -u postgres createdb health_check_db
          sudo -u postgres psql -c "show databases;"
          echo "Waiting for PostgreSQL to start..."
          sleep 10

      - name: Run integration tests
        run: npm test
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_DIALECT: ${{ secrets.DB_DIALECT }}
